### ISSUE TITLE
Custom Media System and XLF file paths

### ISSUE THREAD

**Issue by earleskinner-avast** [Jumoo/Jumoo.TranslationManager.Issues#12]
Hi,

We have a custom media file system which uploads media files to a FTP site. Translation manager will work correctly when creating XLF files (uploaded to FTP). I am assuming the Translation Manager uses the Current Media File System to create files.

But when viewing the job - the download path for the translation file points to the site hostname and does not use the FTP url. Any advise on how to correct the url? Or is it the case that when generating the url - it should use GetMediaUrl()?

Link appearing in "Download File" button - `http://localhost:8081/media/xliff_translations//20210705_103252_en-US_nl-NL.xlf` but it should point to `<ftp site>/media/xliff_translations//20210705_103252_en-US_nl-NL.xlf`

**Comment by KevinJump** [comment]
Hi, 

yeah it turns out the magic is actually done when you upload a file - if you look in umbraco the when you have a blob provider without the virtualpathprovider the fully quailifed url for the media item is stored inside the umbracoFile property. so all GetMediaUrl does is return this or the local /media value .

So we have to ensure we set the url after the file is uploaded and we can do this by calling the file provider GetUrl(path) method, and storing that. 

So this is fixed in 8.7.1 - but only for newly created translation jobs. (as we have to write the full url to the job when we first upload the file). 

https://github.com/Jumoo/Jumoo.TranslationManager.Issues/releases/tag/8.7.1

_you will also need to update clientdependency version as this updated the js files in the connector too._

**Comment by earleskinner-avast** [comment]
Hi. I've tested this and it does now call `GetUrl` from our custom media file system and provides the correct url back. But it seems like it's not saving any url now. The Download File button link is now blank (no href).

**Comment by KevinJump** [comment]
Hi 

Can you confirm that the file /app_plugins/TranslationConnector.Xliff/submittedController.js contains the method : 


```
    function getMediaUrl(properties) {

            if (properties.fileUrl !== undefined)
                return properties.fileUrl;

            return properties.fileLocation;

        }
```

and that this isn't been cached by umbraco or your browser  (incrementing clientdependency should do that bit). 

if it is all there can you break in the browser on this methoid and see what the value of properties.fileUrl is ? 

Kevin

**Comment by earleskinner-avast** [comment]
Sorry, it was browser cache and its working now. Thanks very much.

**Comment by KevinJump** [comment]
👍
