### ISSUE TITLE
Saving translation data tables into another database 

### ISSUE THREAD

**Issue by serbanavast** [Jumoo/Jumoo.TranslationManager.Issues#19]
Hello! 
I have a question, please. Is there a way we can put the translation data tables into another database?
Because when we do a deployment we completely destroy our database, therefore removes the jobs that had already been created. 
Any suggestion for this issue would be appreciated.

**Comment by KevinJump** [comment]
Hi, 

At the moment i think the answer is no its not possible (or that easy) - internally Translation manager is using the Umbraco db connection and methods to put the data in, i am not sure how easy it would be for us to separate the translation tables from that. 

even if it was moved the main issue however would also be how you drop/recreate your tables - because internally Translation manager jobs and nodes will reference the document ids, and property ids that exist in the umbraco tables, if you delete all the data and re-initialize it there will be a chance that the internal IDs are no longer the same ?

**Comment by serbanavast** [comment]
Hello,
Indeed the ids will no longer be the same.
Thank you for the clarifications.

**Comment by KevinJump** [comment]
Hi, i think it would probably make more sense to perform the translations on what ever site you consider the source of the content (e.g stage/dev) as the the ids will presumably won't change as much).
