### ISSUE TITLE
"Error one or more nodes could not be created - Missing target nodes, pages may not be correctly linked" when sending more than 4 nodes for translation

### ISSUE THREAD

**Issue by lassejon** [Jumoo/Jumoo.TranslationManager.Issues#51]
Hello Kevin!

We are using version 10.2.0 of the package.

On our site we are experiencing an issue when trying to send more than 4 content nodes with 'Include children' flag for translation in the 'Bulk Translation' tab. We receive this error message: 

<img width="846" alt="ErrorTargetNodes" src="https://github.com/Jumoo/jumoo-docs/assets/11074864/f6c8c3cb-c0f6-49e4-bb50-9373e49a7c61">

It doesn't seem to matter how many children the nodes have.

We have set up our languages to use the Umbraco Variants feature on a single tree. The Translation Set is setup for only the root node of all our content. Master is the root node in English and Sites are all our configurable languages of the root.

If we remove content nodes to 4 or less, the 'Send to translate' will succeed.

Is this a limitation of the tool, a misconfiguration on our side or an actual bug?

Thanks in advance, 
Lasse Jon

**Comment by KevinJump** [comment]
Hi, 

_I had a load of questions - but i think i have worked it out. we had a very similar issue a while back and i thought we had resolved it._ 


this is a bug, its very speicif and depends on a number of factors, including how many child items you send the grouping of those items. 

in summary, 

internally Translation manager - breaks down the request to create translations into groups of 5 items, 

- so if you send 7 items to translation it will create 5 and then create 2
- if during any of those requests the number of translated nodes comes back as zero, it shows this error (it should be more detailed - but this is 'usually' the issue at this point). 

however if you send something to translation that has zero text elements to translate in it, that will also not return a node. 

so this can occur :  
 - if you send 6 items .. 5 get created and the 6th is created on its own
 - if the 6th item has no translatable content, the request returns zero nodes
 - because zero nodes came back we think its a target error. when its not. 

-- 
so we need to fix that (again!)

possible workarounds :
- ensure translate node name is ticked ? - because this should ensure that every node will always have at least one element for translation. 

or 
-  change the default batch size for node creation (which is 5) - to something else , e.g 25 

in appsettings.json file. 

```json
"Translation": {
    "batchSize": 50
  }
```

- but we will start working on a fix.

**Comment by KevinJump** [comment]
cool - we have a working in principle fix,. that mainly involves moving the error to the right place, there are a number of valid reasons why there might be no translation nodes in a batch and we need to work with that.

**Comment by KevinJump** [comment]
Fix for this on our nightly builds if you require / want to try it. 

https://dev.azure.com/jumoo/Public/_artifacts/feed/nightly/NuGet/Jumoo.TranslationManager/overview/10.2.1-build.20230607.2

**Comment by KevinJump** [comment]
closing as fixed in 10.2.1 and above.
